# Generated by Django 4.1.1 on 2022-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_service_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color_code',
            field=models.CharField(default='#d90769', max_length=30),
        ),
    ]
