# Generated by Django 4.1.1 on 2022-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_service_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icons',
            field=models.CharField(default='bi bi-card-checklist', max_length=20),
        ),
    ]
