# Generated by Django 4.1.1 on 2022-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_service_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icons',
            field=models.CharField(default='bi bi-card-checklist', max_length=50),
        ),
    ]
